# Generated by Django 2.2.5 on 2019-09-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_day',
            new_name='birthdate',
        ),
    ]
